// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpQvBsQ_wAkD4TTki_B4_qnbj9B_ExEjA',
    appId: '1:903678318996:web:721e8bdacb18a3073dd781',
    messagingSenderId: '903678318996',
    projectId: 'raindrop-bb024',
    authDomain: 'raindrop-bb024.firebaseapp.com',
    storageBucket: 'raindrop-bb024.firebasestorage.app',
    measurementId: 'G-YZD4M1Z7P1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRu0WulUHgUgtEET0EGKmZSJSGAiUfEdY',
    appId: '1:907781091981:android:6f599bc915115623f6a8c4',
    messagingSenderId: '907781091981',
    projectId: 'qatrat-matar',
    storageBucket: 'qatrat-matar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzwxzHmN1_xEJVHgcxQUB8fuwdr0KpEyY',
    appId: '1:907781091981:ios:b88de9aa9091322ef6a8c4',
    messagingSenderId: '907781091981',
    projectId: 'qatrat-matar',
    storageBucket: 'qatrat-matar.firebasestorage.app',
    iosBundleId: 'com.qatratmatar.qatratMatarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZZQiNxcws04qU28kuLHSwUfCfkiJKoq4',
    appId: '1:903678318996:ios:48ead24c02973bdf3dd781',
    messagingSenderId: '903678318996',
    projectId: 'raindrop-bb024',
    storageBucket: 'raindrop-bb024.firebasestorage.app',
    iosBundleId: 'com.digicrea.rain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpQvBsQ_wAkD4TTki_B4_qnbj9B_ExEjA',
    appId: '1:903678318996:web:76905236e986af1b3dd781',
    messagingSenderId: '903678318996',
    projectId: 'raindrop-bb024',
    authDomain: 'raindrop-bb024.firebaseapp.com',
    storageBucket: 'raindrop-bb024.firebasestorage.app',
    measurementId: 'G-J5TL37KTF6',
  );
}